### ISSUE TITLE
scope.whenNotVisible is not a function

### ISSUE THREAD

**Issue by jagged3dge** [rpocklin/angular-scroll-animate#1]
**Problem:** `scope.whenNotVisible is not a function` is thrown if the `when-not-visible` attribute is omitted in the template markup.

Thank you for making this lovely gem of a directive. Much lighter than in-view too :)
However, here's a snag that I hit. I have this markup:

``` html
<div class="community-posts" when-visible="loadPosts">
  <!-- community post content here -->
</div>
```

and here's my relevant code from the controller:

``` js
var loadPosts = function ($el) {
  var posts = [{id: 1, content: 'foo bar'}, {id: 2, content: 'bar foo'}];
  return posts;
};
$scope.loadPosts = loadPosts;
```

But when I view the page, it throws this error in the console:

```
TypeError: scope.whenNotVisible is not a function
```

This line is where the debugger points to:

``` js
determineWhereElementIsInViewport(el, viewportHeight,
            scope.whenVisible(), scope.whenNotVisible(), delayPercent, scope);
```

This most likely has to do with how the reference to the `whenVisible` and `whenNotVisible` functions are passed around in the directive. If the `when-not-visible` attribute is omitted, `scope.whenNotVisible` itself remains `undefined` causing this error being thrown.

**Comment by rpocklin** [comment]
Thanks really appreciate the effort for this feedback, i'll take a look in detail in the next day or so.

**Comment by rpocklin** [comment]
I've fixed up the detection of these functions and updated ngdocs and bumped to `v0.9.2` - here's the commit a3c190b7cf0c5cbc4dd6e29b453e6e40091acee8 - thanks for finding this.

**Comment by jagged3dge** [comment]
Thanks for the quick update @rpocklin 

However, with the new 0.9.3 release, the issue is back, albeit at a different line. The attribute `when-not-visible` is not optional any more.
If I do not specify the `when-not-visible` attribute at all, it throws an error:

```
Uncaught TypeError: whenNotVisibleFn is not a function
```

Seems like a scoping issue. Instead of it defaulting to `angular.noop`, the value of `whenNotVisibleFn` returns `undefined`.

This is the line the debugger errors at:

```
        else if (!($el.data('hidden')) && (panelBottom < 0 || panelTop > viewportHeight)) {
          whenNotVisibleFn($el, scope); // <= this line no. 63
          $el.data('hidden', true);
        }
```

**Comment by rpocklin** [comment]
Apologies - see `v0.9.4` for the fix.  For real this time :+1:

**Comment by jagged3dge** [comment]
Lovely little fix. Thanks for the quick update!
