### ISSUE TITLE
Bug with parent container of height: 100 vh or 100 %

### ISSUE THREAD

**Issue by stefanoTron** [rpocklin/angular-scroll-animate#3]
Hi,

In my use case I have a parent div with a height of 100 vh, this makes the animation buggy. It looks like the 'scroll' event is not fired, so on page load the animation looks good and on resize it works as well. If I remove the 100 vh, everything is back to normal.  Same thing happens with 100%.

**Comment by rpocklin** [comment]
not sure what 100vh means but if you send me a plukr or code I can take a look.

**Comment by stefanoTron** [comment]
I'll setup a plnkr shortly, in the mean time check out [http://www.w3.org/TR/css3-values/#viewport-relative-lengths](http://www.w3.org/TR/css3-values/#viewport-relative-lengths) for the viewport percentage unit.

**Comment by stefanoTron** [comment]
here you go: [http://plnkr.co/edit/kRtMO3mzwKFI3YwkNFyA?p=preview](http://plnkr.co/edit/kRtMO3mzwKFI3YwkNFyA?p=preview)

I noticed that using flexbox also seams to be part of the problem.

So to summerize: 
flexbox + 100vh --> buggy 
flexbox + 100% --> buggy 
just 100vh without flexbox --> ok 
flexbox with pixel height (say 1000px) or auto --> ok

hope this helps :)

**Comment by Ross-Rawlins** [comment]
I have given it a set height and it still doenst run the animate element function. It only runs it on load. Please help. If I resize the browser window then it picks up teh event and animates the items.

**Comment by umdstu** [comment]
I think I'm experiencing the same issue. Things seem to work fine until they are scrolled back into view, in which case they do not animate back in. Adding some log statements it's clear that when-visible function is not even firing when the elements are scrolled back into view after having been hidden. Using this bootstrap.

**Comment by rpocklin** [comment]
Haven't had time to debug this yet, but i'm expecting either the `getBoundingClientRect()` doesn't play nice with those CSS settings or the calculations don't work as expected in those cases.

Armed with the plunkr, i'll take a look in the next few days.

**Comment by rpocklin** [comment]
Problem appears to be the DOM not triggering 'scroll' events when.  Culprit is `overflow: auto` with `flexbox` and `vh` (every other combination works in Chrome).

Biggest issue is it is browser specific, Chrome works one way, Safari works another.  Need to investigate more to have a global solution.

**Comment by Ross-Rawlins** [comment]
Thanks for doing this fix. I would like to use it on a production app so if you find the bug in time it would be awesome.

**Comment by rpocklin** [comment]
Check out v0.9.8 and specify the `bind-scroll-to` documentation, this should fix it cross-browser.

**Comment by Ross-Rawlins** [comment]
I just downloaded it and its not working still...still the same thing where it doesnt update on scroll. I am using it in IONIC and with angular material with no luck,

**Comment by rpocklin** [comment]
You will need to be more specific, ie. what css styles and structure you are using.  Which browsers are you using?

**Comment by Ross-Rawlins** [comment]
I am using chrome. And the height is set using 100%; no auto

**Comment by rpocklin** [comment]
Rather than me guessing your HTML structure and css classes, perhaps you can provide them and I can offer help.  Plunkr is good here.

**Comment by rpocklin** [comment]
@littletower here is your plunkr, with v0.9.8 of this directive and `bind-scroll-to` specified, which fixes the issue.  http://plnkr.co/edit/vW7oan30HIPjqpe4OOEq?p=preview

**Comment by stefanoTron** [comment]
thanks! works fine for me.

**Comment by Duovili** [comment]
<timeline>
            <timeline-event ng-repeat="item in user.activity" bind-scroll-to=".timeline-item"  when-visible="animateElementIn" when-not-visible="animateElementOut" class="hidden timeline-item">
                <timeline-badge class="hidden">
                    <i class="glyphicon info"></i>
                </timeline-badge>
                <timeline-panel class="bounce-in">
                    <md-list-item class="md-3-line" >
                        <img ng-src="{{(item.imagePath) || item.brandPath}}" class="md-avatar" alt="{{item.name}}" />
                        <div class="md-list-item-text" layout="column">
                            <timeline-heading>
                                <h3 ><strong class="positive">{{item.name}}</strong><span class="pull-right"><i class="icon ion-clock"></i> {{(item.date| myDateFormat) | timeago}}</span></h3>
                            </timeline-heading>
                            <progressbar max="100" value="100"></progressbar>
                            <h4>{{item.content}}</h4>
                        </div>
                    </md-list-item>
                </timeline-panel>
            </timeline-event>
        </timeline>

I am using hte above code and I cannot get it to work. what am I missing?

**Comment by Ross-Rawlins** [comment]
I still cant get it to work, what am I doing wrong here?
![screen shot 2015-11-05 at 8 51 06 am](https://cloud.githubusercontent.com/assets/3350096/10961738/68c4d566-839a-11e5-9bdb-8259762329bd.png)

**Comment by rpocklin** [comment]
@Duovili your `bind-scroll-to` should be a parent element of `timeline` not a child element.

**Comment by Ross-Rawlins** [comment]
thanks that solved it. and thank you for being so quick to respond.

**Comment by SylTi** [comment]
I have the same problem. I use flexbox, and your solution doesn't seems to work.
My structure looks like that : 
html : 
`<body id="top" ng-controller="MainCtrl as main">
<div class="container child">
        <div class="row hidden" when-visible="main.animateElementIn" when-not-visible="main.animateElementOut" bind-scroll-to=".child">`

Js : 
`   var vm = this;

```
vm.animateElementIn = animateElementIn;
    vm.animateElementOut = animateElementOut;

    function animateElementIn($el) {
        console.log('animeIn');
        $el.removeClass('hidden');
        $el.addClass('animated slideInLeft'); 
    };

    function animateElementOut($el) {
        console.log('animeOut');
        $el.addClass('hidden');
        $el.removeClass('animated slideInLeft');
    };`
```

The callbacks never get fired.
Any idea ? Thanks in advance.
